version: "3.8"
services:
  sonarqube:
    build: ./
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres/sonar
    ports:
      - "9000:9000"
    volumes:
      - sonar:/opt/sonarqube/data
    links:
      - postgres
  postgres:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
  sonar:
